from enum import Enum


class MotivoDesligamentoEnum(str, Enum):
    TERMINO_CONTRATO = "TERMINO_CONTRATO"
    DESISTENCIA_ESTAGIARIO = "DESISTENCIA_ESTAGIARIO"
    CONCLUSAO_CURSO = "CONCLUSAO_CURSO"
    SOLICITACAO_UNIDADE = "SOLICITACAO_UNIDADE"
    BAIXO_DESEMPENHO = "BAIXO_DESEMPENHO"
    INASSIDUIDADE = "INASSIDUIDADE"
    OUTROS = "OUTROS"

class SexoEnum(str, Enum):
    MASCULINO = "M"
    FEMININO = "F"
    NAO_INFORMADO = "N"

class AvaliacaoSupervisorEnum(str, Enum):
    INSUFICIENTE = "INSUFICIENTE"
    SATISFATORIO = "SATISFATORIO"
    BOM = "BOM"
    PLENAMENTE_SATISFATORIO = "PLENAMENTE_SATISFATORIO"


