from enum import Enum


class MotivoDesligamentoEnum(str, Enum):
    TERMINO_CONTRATO = "TERMINO_CONTRATO"
    DESISTENCIA_ESTAGIARIO = "DESISTENCIA_ESTAGIARIO"
    CONCLUSAO_CURSO = "CONCLUSAO_CURSO"
    SOLICITACAO_UNIDADE = "SOLICITACAO_UNIDADE"
    BAIXO_DESEMPENHO = "BAIXO_DESEMPENHO"
    INASSIDUIDADE = "INASSIDUIDADE"
    OUTROS = "OUTROS"

class SexoEnum(str, Enum):
    MASCULINO = "M"
    FEMININO = "F"
    NAO_INFORMADO = "N"

class ClassificacaoEstagioEnum(str, Enum):
    ENSINO_MEDIO = "ENSINO_MEDIO"
    TECNICO = "TECNICO"
    SUPERIOR = "SUPERIOR"
    POS_GRADUACAO = "POS_GRADUACAO"
