from enum import Enum


class MotivoDesligamentoEnum(str, Enum):
    TERMINO_CONTRATO = "TERMINO_CONTRATO"
    DESISTENCIA_ESTAGIARIO = "DESISTENCIA_ESTAGIARIO"
    CONCLUSAO_CURSO = "CONCLUSAO_CURSO"
    SOLICITACAO_UNIDADE = "SOLICITACAO_UNIDADE"
    BAIXO_DESEMPENHO = "BAIXO_DESEMPENHO"
    INASSIDUIDADE = "INASSIDUIDADE"
    OUTROS = "OUTROS"
